version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.5.3-node-browsers
         environment:
           - RAILS_ENV=test
           - DATABASE_URL=postgres://username@localhost:5432/bookstore_test
       - image: circleci/postgres:11
         environment:
           - POSTGRES_USER=username
           - POSTGRES_DB=bookstore_test

    working_directory: ~/repo

steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-{{ checksum "Gemfile.lock" }}
            - rails-demo-

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - run: sudo apt install -y postgresql-client || true

      # Store bundle cache
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            
            bundle exec rspec \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $TEST_FILES
      # Undercover
      - run:
          name: Check coverage
          command: |
            gem install undercover
            undercover --compare origin/develop
          
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

general:
  branches:
    only:
     - develop # list of branches to build