default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials.username %>
  password: <%= Rails.application.credentials.password %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: bookstore_develop

test:
  <<: *default
  database: bookstore_test

production:
  <<: *default
  database: bookstore_production